
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.daniel.ejemplojflex.parser;

/** CUP generated class containing symbol constants. */
public class SimpleParserSym {
  /* terminals */
  public static final int MINUS = 3;
  public static final int INTEGER = 6;
  public static final int LPAR = 7;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int SYM = 9;
  public static final int TIMES = 4;
  public static final int RPAR = 8;
  public static final int DIVIDES = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDES",
  "INTEGER",
  "LPAR",
  "RPAR",
  "SYM"
  };
}

